# apiHost: albh3.aitmed.io
# apiHost: ecosapip1.aitmed.io
apiHost: api.aitmed.com.cn
apiPort: 443
webApiHost: apiHost
appApiHost: apiHost
connectiontimeout: '5'
loadingLevel: 1
debug: console_log_api
isGetPosition: false
syncHost: https://sync.aitmed.io:443
elasticClient: https://elastic.aitmed.io
searchLink: https://search.aitmed.com
platform: admin
superAdminID: "Xa2FfgAAAAAI8AJCrBIABQ==" 
whisperUrl: https://ecosapip1.aitmed.us:9002/asr
transcriptionUrl: https://ecosapip1.aitmed.us:9002/asr
preloadlib: 
  - https://cdn.staticfile.org/echarts/5.4.1/echarts.min.js
  - https://sdk.twilio.com/js/video/releases/2.14.0/twilio-video.min.js
  - https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.js
  - https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.2/html2canvas.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js
viewWidthHeightRatio:
    min: 1.78 # iphone 12 9:19.5 Samsung Galaxy A71 5G 9:20
    max: 1.78 # normal 3:4 ratio ipad
web:
  cadlVersion:
    stable: 8.49.2
    test: 8.49.2
ios:
  cadlVersion:
    stable: 8.49.2
    test: 8.49.2
android:
  cadlVersion:
    stable: 8.49.2
    test: 8.49.2
cadlBaseUrl: ../cadl/admin/admin/
cadlMain: cadlEndpoint.yml
timestamp: 09182021