name: AiTmed
title: AiTmed | Start your E-health Journey Anywhere, Anytime
description: Anyone, Anywhere, Anytime Start Your E-health Journey With Us
favicon: ./public/favicon.ico # Relative path starting from ./apps/web
injectScripts: ./public/libs.html # Relative path starting from ./apps/web
keywords:
  - accommodate
  - account
  - admin
  - advance
  - aitmed
  - appointment
  - appointments
  - availability
  - barriers
  - best
  - between
  - blockchain
  - breaking
  - care
  - choose
  - chosen
  - chronic
  - clinic
  - cloud
  - communication
  - company
  - complete
  - compliance
  - connect
  - connecting
  - contact
  - convenient
  - coordination
  - covid19
  - create
  - custom
  - customized
  - data
  - date
  - dates
  - deliver
  - dermatology
  - directly
  - doctor
  - doctors
  - documentation
  - e-health
  - e-prescription
  - e-referral
  - ecosystem
  - efficiently
  - everyone
  - exchange
  - facilities
  - fast
  - healthcare
  - high
  - hipaa
  - hospital
  - house
  - illness
  - imaging
  - improve
  - improving
  - insurance
  - knowledge
  - lab
  - location
  - lost
  - make
  - manage
  - management
  - marketing
  - matching
  - maximize
  - medical
  - meeting
  - needs
  - network
  - neurology
  - noodl
  - online
  - organizations
  - pandemic
  - patient
  - patient-provider-organization
  - patient’s
  - pediatric
  - people
  - physician
  - plan
  - platform
  - power
  - practice
  - private
  - professional
  - profile
  - program
  - provider
  - providers
  - quality
  - radiology
  - reach
  - referral
  - reputation
  - resources
  - room
  - schedule
  - scheduling
  - search
  - secure
  - secures
  - selected
  - self
  - senior
  - services
  - share
  - sign
  - specialist
  - support
  - symptoms
  - technology
  - telecommunication
  - telehealth
  - telemedicine
  - tools
  - top-rated
  - urgent
  - virtual
  - visit
  - vital
  - waiting
  - wellness
  - works
  - worldwide
