vars:
  componentType:
    - button
    - canvas
    - chart
    - chatList
    - ecosDoc
    - divider
    - footer
    - header
    - image
    - label
    - list
    - listItem
    - map
    - page
    - plugin
    - pluginHead
    - pluginBodyTail
    - popUp
    - register
    - select
    - scrollView
    - textField
    - textView
    - video
    - view
  emitTrigger:
    - path
    - dataKey
    - dataValue
    - placeholder
    - postMessage
    - register
  node: ${node}
  userEvent:
    - onBlur
    - onClick
    - onChange
    - onFocus
    - onHover
    - onInput
    - onMouseEnter
    - onMouseLeave
    - onMouseOut
    - onMouseOver
    - onLazyLoading
identifiers:
  - =.builtIn.validate.isImage:
      condition:
        - if:
          - =.builtIn.object.objectHasValue:
            dataIn:
              objArr: []
          - continue
          - false
        - if:
          - =.builtIn.object.hasMultipleKeys:
            dataIn:
              object: ${node}
              keyArr: ['type', 'path']
          - true
          - false
      assert:
        - =.builtIn.validate.object:
          dataIn: ${node}
        - =.builtIn.object.hasMultipleKeys:
          dataIn:
            object: ${node}
            keyArr: ['path']
diagnostics:
  - key:
      - ..vars.emitTrigger
      - ..vars.userEvent
    nullable: false
    type:
      - Array
      - Object
  - key:
      - ${componentType}
    nullable: false
    type:
      - Object
  - code: 40000
    description: The component
    if:
      - =.builtIn.object.has:
          dataIn:
            object: ..node
            key: onClick
      - if:
        - =.builtIn.string.equal:
            dataIn:
              string1: ..one
              string2: two
      - continue
