vars:
  - componentType:
    - button
    - canvas
    - chart
    - chatList
    - ecosDoc
    - divider
    - footer
    - header
    - image
    - label
    - list
    - listItem
    - map
    - page
    - plugin
    - pluginHead
    - pluginBodyTail
    - popUp
    - register
    - select
    - scrollView
    - textField
    - textView
    - video
    - view
  - emitTrigger:
    - path
    - dataKey
    - dataValue
    - placeholder
    - postMessage
    - register
  - userEvent:
    - onBlur
    - onClick
    - onChange
    - onFocus
    - onHover
    - onInput
    - onMouseEnter
    - onMouseLeave
    - onMouseOut
    - onMouseOver
    - onLazyLoading
diagnostics:
  - key:
      - ${emitTrigger}
      - ${userEvent}
    nullable: false
    type:
      - Array
      - Object
  - key:
      - ${componentType}
    nullable: false
    type:
      - Object
