const DataSource = new Map([
    ["Patient Name", {'Source': 'Appointment lobby', 'Expansion': 'Patient Name: First Name or Middle Name or Last Name'}],
    ["Patient DOB", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Date of Birth'}],
    ["Patient SEX", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Gender'}],
    ["Patient Gender", {'Source': 'Appointment lobby ', 'Expansion': 'undefined'}],
    ["Patient Phone Number", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Phone #'}],
    ["Patient Address", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Address'}],
    ["Patient Email", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Email'}],
    ["Patient Alternate Phone Number", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Alternate Phone #'}],
    ["Emergency Contact Name", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Emergency Contac Name: First Name, Middle Name, Last Name'}],
    ["Emergency Contact Relation", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Emergency Contact Relation'}],
    ["Emergency Contact Phone Number", {'Source': 'Appointment lobby ', 'Expansion': 'Patient Emergency Contact Phone #'}],
    ["ID Type", {'Source': 'Appointment lobby ', 'Expansion': 'Patient ID Type'}],
    ["ID Number", {'Source': 'Appointment lobby ', 'Expansion': 'Patient ID #'}],
    ["ID Image", {'Source': 'Appointment lobby ', 'Expansion': 'Patient ID Image'}],
    ["Visit Type", {'Source': 'Appointment lobby ', 'Expansion': 'Appointment Visit Type'}],
    ["Reason", {'Source': 'Appointment lobby ', 'Expansion': 'Appointment Reason for Visit'}],
    ["Date or Date of service", {'Source': 'Appointment lobby ', 'Expansion': 'Appointment Date, Date of Exam'}],
    ["Appointment Time", {'Source': 'Appointment lobby ', 'Expansion': 'Appointment Time'}],
    ["Payer Name", {'Source': 'Financial Responsibility', 'Expansion': 'Primary Insurance Payer Name'}],
    ["Payer ID", {'Source': 'Financial Responsibility', 'Expansion': 'Primary Insurance Payer ID'}],
    ["Payer Address", {'Source': 'Financial Responsibility', 'Expansion': 'Primary Insurance Payer Address'}],
    ["Insurance Type", {'Source': 'Financial Responsibility', 'Expansion': 'Insurance Type, Primary Insurance Insurance Type'}],
    ["Insured ID Number", {'Source': 'Financial Responsibility', 'Expansion': 'Insured ID #, Claim #(Workers Comp)'}],
    ["Health Plan ID", {'Source': 'Financial Responsibility', 'Expansion': 'undefined'}],
    ["Insured Name", {'Source': 'Financial Responsibility', 'Expansion': 'Relationship To Patient->name, Payer Name(Workers Comp)'}],
    ["Patient Relationship to Insured", {'Source': 'Financial Responsibility', 'Expansion': 'Relationship To Patient, Self(Workers Comp)'}],
    ["Insured Address", {'Source': 'Financial Responsibility', 'Expansion': 'Relationship is Self: Patient Address, Relationship is spouse/child/other: Relationship -> Address, Employment Address(Workers Comp)'}],
    ["Insured's Date of Birth", {'Source': 'Financial Responsibility', 'Expansion': 'Relationship is self： Patient date of birth, Gender; Relationship is spouse/child/other: relationship->Date of Birth, Gender'}],
    ["Insured's Sex", {'Source': 'Financial Responsibility', 'Expansion': 'Relationship is self： Patient Gender; Relationship is spouse/child/other: relationship->Gender'}],
    ["Other Insured Name", {'Source': 'Financial Responsibility', 'Expansion': 'Secondary Insurance: Relationship is self: patient name, Relationship is spouse/child/other: relationship->name'}],
    ["Secondary Insured Name", {'Source': 'Financial Responsibility', 'Expansion': 'undefined'}],
    ["Other Insured's Policy or Group Number", {'Source': 'Financial Responsibility', 'Expansion': 'Secondary Insurance: Group #'}],
    ["Secondary Insurance Group Number", {'Source': 'Financial Responsibility', 'Expansion': 'undefined'}],
    ["Insurance Plan Name or Program Name", {'Source': 'Financial Responsibility', 'Expansion': 'Insurance Plan/Medical Group'}],
    ["Group Name", {'Source': 'Financial Responsibility', 'Expansion': 'undefined'}],
    ["Secondary Insurance Plan Name or Program Name", {'Source': 'Financial Responsibility', 'Expansion': 'Secondary Insurance: Insurance Plan/Medical Group'}],
    ["Insured policy group or FECA number", {'Source': 'Financial Responsibility', 'Expansion': 'Group #'}],
    ["Insurance Group No", {'Source': 'Financial Responsibility', 'Expansion': 'undefined'}],
    ["Accident State", {'Source': 'Financial Responsibility', 'Expansion': 'Medical Insurance:--; Personal Injury: Auto accident: State, Other accident: --'}],
    ["Subscriber Information", {'Source': 'Financial Responsibility', 'Expansion': 'Patient Name, Patient Address'}],
    ["Occupation", {'Source': 'Fin. Resp Form -> Worker Comp', 'Expansion': 'Occupation'}],
    ["Provider Name", {'Source': 'Provider Profile', 'Expansion': 'Provider Name:First Name, Middle Name, Last Name, Title/Training'}],
    ["Specialty", {'Source': 'Provider Profile', 'Expansion': 'Provider Specialty'}],
    ["Provider Gender", {'Source': 'Provider Profile', 'Expansion': 'Provider Gender'}],
    ["Provider Medical License Number", {'Source': 'Provider Profile', 'Expansion': 'Provider Medical License Number'}],
    ["Provider Medical License State", {'Source': 'Provider Profile', 'Expansion': 'Provider Medical License State'}],
    ["Provider Medical License Expiration", {'Source': 'Provider Profile', 'Expansion': 'Provider Medical License Expiration'}],
    ["LIC Number", {'Source': 'Provider Profile', 'Expansion': 'Provider Medical License ：State+Medical license #'}],
    ["Provider NPI Number", {'Source': 'Provider Profile', 'Expansion': 'Provider NPI #'}],
    ["Provider DEA Number", {'Source': 'Provider Profile', 'Expansion': 'Provider DEA #'}],
    ["Facility Name", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Name'}],
    ["Main Phone Number", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Main Phone #'}],
    ["Facility Address", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Address'}],
    ["Facility Email", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Email'}],
    ["Facility Business License Number", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Business License #'}],
    ["Facility Business License City and State", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Business License City&State'}],
    ["Facility Business License Expiration Date", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Business License Expiration Date'}],
    ["Facility NPI Number", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility NPI #'}],
    ["Facility DEA Number", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility DEA #'}],
    ["Fed Tax No", {'Source': 'Medical Facility Profile', 'Expansion': 'TIN(EIN) #'}],
    ["Federal Tax ID Number", {'Source': 'Medical Facility Profile', 'Expansion': 'undefined'}],
    ["Facility Fax Number", {'Source': 'Medical Facility Profile', 'Expansion': 'Facility Fax #'}],
    ["Hospitalization Dates", {'Source': 'Superbill', 'Expansion': 'Hospitalization Dates Related to Current Services'}],
    ["Outside Lab", {'Source': 'Superbill', 'Expansion': 'Outside Lab'}],
    ["Diagnosis or Nature of Illness or Injury", {'Source': 'Superbill', 'Expansion': 'Diagnosis'}],
    ["Primary Diag Code or Other Diag Code", {'Source': 'Superbill', 'Expansion': 'undefined'}],
    ["Treatment Authorization Codes", {'Source': 'Superbill', 'Expansion': 'Prior Authorization Number'}],
    ["Prior Authorization Number", {'Source': 'Superbill', 'Expansion': 'undefined'}],
    ["Place of Service", {'Source': 'Superbill', 'Expansion': 'Place of Service'}],
    ["Procedures or Services or Supplies", {'Source': 'Superbill', 'Expansion': 'Procedure Code, Modifiers'}],
    ["HCPCS or Rate or HCPCS Code", {'Source': 'Superbill', 'Expansion': 'undefined'}],
    ["Diagnosis Pointers", {'Source': 'Superbill', 'Expansion': 'ICD`s'}],
    ["Charges", {'Source': 'Superbill', 'Expansion': 'Procedure Code/Charge'}],
    ["Days or Unites", {'Source': 'Superbill', 'Expansion': 'Quantity'}],
    ["Srv Units", {'Source': 'Superbill', 'Expansion': 'undefined'}],
    ["Total Charges", {'Source': 'Superbill', 'Expansion': 'Service charge × Quantity = total charge per line'}],
    ["Service Facility Location information", {'Source': 'Superbill', 'Expansion': 'Service Facility Location Information-> Name、address'}],
    ["Service Facility Location NPI", {'Source': 'Superbill', 'Expansion': 'Service Facility Location Information-> NPI'}],
    ["Service Facility ID", {'Source': 'Superbill', 'Expansion': 'Service Facility Location Information-> Tax ID'}],
    ["Rev Cd", {'Source': 'Superbill', 'Expansion': 'Revenue Code'}],
    ["Description", {'Source': 'Superbill', 'Expansion': 'Description'}],
    ["Blood Pressure", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Blood Pressure  '}],
    ["Heart Rate", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Heart Rate '}],
    ["Respiratory Rate", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Respiratory Rate'}],
    ["Pulse Oximetry", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Pulse Oximetry '}],
    ["Temperature", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Temperature'}],
    ["Blood Glucose levels", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Blood Glucose levels  '}],
    ["Height", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Height'}],
    ["Weight", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Weight'}],
    ["Body Mass Index(BMI)", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Patient Body Mass Index(BMI)'}],
    ["Past Medical History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Past Medical History'}],
    ["Allergies", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Allergies'}],
    ["Current Medications", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Current Medications'}],
    ["Immunizations", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Immunizations'}],
    ["Hospitalizations", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Hospitalizations'}],
    ["Surgical History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Surgical History'}],
    ["Family History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Family History'}],
    ["Obstetrical History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Obstetrical History'}],
    ["Sexual History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Sexual History'}],
    ["Social History", {'Source': 'Appointment looby>Medical History', 'Expansion': 'Social History'}],
    ["Signature", {'Source': 'User', 'Expansion': 'User Signature, Signature box'}],
    ["Vital Sign", {'Source': 'Appointment looby>Remote health', 'Expansion': 'Appointment Looby Vital Sign'}],
    ["Patient info", {'Source': 'Appointment looby', 'Expansion': 'Patient Name, Date of Birth, Phone #, Email, Patient Address'}],
    ["Provider info", {'Source': 'User ', 'Expansion': 'Provider name, Provider title, Provider Specialities, LIC #, NPI #, DEA #\nFacility Email, Fax #, Main #, Address'}],
    ["Facility info", {'Source': 'Medical Facility Profile', 'Expansion': 'Medical Facility photo, Name, Address, Email, Website, Main #, Fax #'}],
    ["Date", {'Source': 'undefined', 'Expansion': 'Today Date, Date selection box'}],
    ["Time", {'Source': 'undefined', 'Expansion': 'Time selection box'}],
])

export default DataSource