const DataSource = new Map([
    ["Patient Name", {"Source":"Appointment lobby","Expansion":"Patient Name: First Name or Middle Name or Last Name","isSharp":false}],
    ["Patient User Name", {"Source": "Appointment lobby","Expansion":"Patient User Name","isSharp":false}],
    ["Patient DOB", {"Source":"Appointment lobby ","Expansion":"Patient Date of Birth","isSharp":false}],
    ["Patient Age", {"Source":"Appointment lobby ","Expansion":"Year(Now)-Patient Date of Birth","isSharp":false}],
    ["Patient SEX", {"Source":"Appointment lobby ","Expansion":"Patient Gender","isSharp":false}],
    ["Patient Gender", {"Source":"Appointment lobby ","Expansion":"Patient Gender","isSharp":false}],
    ["Patient Phone Number", {"Source":"Appointment lobby ","Expansion":"Patient Phone #","isSharp":false}],
    ["Patient Address", {"Source":"Appointment lobby ","Expansion":"Patient Address","isSharp":false}],
    ["Patient Email", {"Source":"Appointment lobby ","Expansion":"Patient Email","isSharp":false}],
    ["Patient Alternate Phone Number", {"Source":"Appointment lobby ","Expansion":"Patient Alternate Phone #","isSharp":false}],
    ["Emergency Contact Name", {"Source":"Appointment lobby ","Expansion":"Patient Emergency Contac Name: First Name, Middle Name, Last Name","isSharp":false}],
    ["Emergency Contact Relation", {"Source":"Appointment lobby ","Expansion":"Patient Emergency Contact Relation","isSharp":false}],
    ["Emergency Contact Phone Number", {"Source":"Appointment lobby ","Expansion":"Patient Emergency Contact Phone #","isSharp":false}],
    ["ID Type", {"Source":"Appointment lobby ","Expansion":"Patient ID Type","isSharp":false}],
    ["ID Number", {"Source":"Appointment lobby ","Expansion":"Patient ID #","isSharp":false}],
    // ["ID Image", {"Source":"Appointment lobby ","Expansion":"Patient ID Image","isSharp":false}],
    ["Visit Type", {"Source":"Appointment lobby ","Expansion":"Appointment Visit Type","isSharp":false}],
    ["Reason", {"Source":"Appointment lobby ","Expansion":"Appointment Reason for Visit","isSharp":false}],
    ["Date or Date of service", {"Source":"Appointment lobby ","Expansion":"Appointment Date, Date of Exam","isSharp":false}],
    ["Appointment Time", {"Source":"Appointment lobby ","Expansion":"Appointment Time","isSharp":false}],
    ["Payer Name", {"Source":"Financial Responsibility","Expansion":"Primary Insurance Payer Name","isSharp":false}],
    ["Payer ID", {"Source":"Financial Responsibility","Expansion":"Primary Insurance Payer ID","isSharp":false}],
    ["Payer Address", {"Source":"Financial Responsibility","Expansion":"Primary Insurance Payer Address","isSharp":false}],
    ["Insurance Type", {"Source":"Financial Responsibility","Expansion":"Insurance Type, Primary Insurance Insurance Type","isSharp":false}],
    ["Insured ID Number", {"Source":"Financial Responsibility","Expansion":"Insured ID #, Claim #(Workers Comp)","isSharp":false}],
    ["Health Plan ID", {"Source":"Financial Responsibility","Expansion":"Insured ID #, Claim #(Workers Comp)","isSharp":false}],
    ["Insured Name", {"Source":"Financial Responsibility","Expansion":"Relationship To Patient->name, Payer Name(Workers Comp)","isSharp":false}],
    ["Patient Relationship to Insured", {"Source":"Financial Responsibility","Expansion":"Relationship To Patient, Self(Workers Comp)","isSharp":false}],
    ["Insured Address", {"Source":"Financial Responsibility","Expansion":"Relationship is Self: Patient Address, Relationship is spouse/child/other: Relationship -> Address, Employment Address(Workers Comp)","isSharp":false}],
    ["Insured's Date of Birth", {"Source":"Financial Responsibility","Expansion":"Relationship is self: Patient date of birth, Gender; Relationship is spouse/child/other: relationship->Date of Birth, Gender","isSharp":false}],
    ["Insured's Sex", {"Source":"Financial Responsibility","Expansion":"Relationship is self: Patient Gender; Relationship is spouse/child/other: relationship->Gender","isSharp":false}],
    ["Other Insured Name", {"Source":"Financial Responsibility","Expansion":"Secondary Insurance: Relationship is self: patient name, Relationship is spouse/child/other: relationship->name","isSharp":false}],
    ["Secondary Insured Name", {"Source":"Financial Responsibility","Expansion":"Secondary Insurance: Relationship is self: patient name, Relationship is spouse/child/other: relationship->name","isSharp":false}],
    ["Other Insured's Policy or Group Number", {"Source":"Financial Responsibility","Expansion":"Secondary Insurance: Group #","isSharp":false}],
    ["Secondary Insurance Group Number", {"Source":"Financial Responsibility","Expansion":"Secondary Insurance: Group #","isSharp":false}],
    ["Insurance Plan Name or Program Name", {"Source":"Financial Responsibility","Expansion":"Insurance Plan/Medical Group","isSharp":false}],
    ["Group Name", {"Source":"Financial Responsibility","Expansion":"Insurance Plan/Medical Group","isSharp":false}],
    ["Secondary Insurance Plan Name or Program Name", {"Source":"Financial Responsibility","Expansion":"Secondary Insurance: Insurance Plan/Medical Group","isSharp":false}],
    ["Insured policy group or FECA number", {"Source":"Financial Responsibility","Expansion":"Group #","isSharp":false}],
    ["Insurance Group No", {"Source":"Financial Responsibility","Expansion":"Group #","isSharp":false}],
    ["Accident State", {"Source":"Financial Responsibility","Expansion":"Medical Insurance:--; Personal Injury: Auto accident: State, Other accident: --","isSharp":false}],
    ["Subscriber Information", {"Source":"Financial Responsibility","Expansion":"Patient Name, Patient Address","isSharp":false}],
    ["Occupation", {"Source":"Fin. Resp Form -> Worker Comp","Expansion":"Occupation","isSharp":false}],
    ["Provider Name", {"Source":"Provider Profile","Expansion":"Provider Name:First Name, Middle Name, Last Name, Title/Training","isSharp":false}],
    ["Provider User Name", {"Source":"Provider Profile","Expansion":"Provider User Name","isSharp":false}],
    ["Provider Email", {"Source":"Provider Profile","Expansion":"Provider Email","isSharp":false}],
    ["Specialty", {"Source":"Provider Profile","Expansion":"Provider Specialty","isSharp":false}],
    ["Provider Gender", {"Source":"Provider Profile","Expansion":"Provider Gender","isSharp":false}],
    ["Provider Medical License Number", {"Source":"Provider Profile","Expansion":"Provider Medical License Number","isSharp":false}],
    ["Provider Medical License State", {"Source":"Provider Profile","Expansion":"Provider Medical License State","isSharp":false}],
    ["Provider Medical License Expiration", {"Source":"Provider Profile","Expansion":"Provider Medical License Expiration","isSharp":false}],
    ["LIC Number", {"Source":"Provider Profile","Expansion":"Provider Medical License :State+Medical license #","isSharp":false}],
    ["Provider NPI Number", {"Source":"Provider Profile","Expansion":"Provider NPI #","isSharp":false}],
    ["Provider DEA Number", {"Source":"Provider Profile","Expansion":"Provider DEA #","isSharp":false}],
    ["Facility Name", {"Source":"Medical Facility Profile","Expansion":"Facility Name","isSharp":false}],
    ["Main Number", {"Source":"Medical Facility Profile","Expansion":"Facility Main #","isSharp":false}],
    ["Facility Address", {"Source":"Medical Facility Profile","Expansion":"Facility Address","isSharp":false}],
    ["Facility Email", {"Source":"Medical Facility Profile","Expansion":"Facility Email","isSharp":false}],
    ["Facility Website", {"Source":"Medical Facility Profile","Expansion":"Facility Website","isSharp":false}],
    ["Facility Business License Number", {"Source":"Medical Facility Profile","Expansion":"Facility Business License #","isSharp":false}],
    ["Facility Business License City and State", {"Source":"Medical Facility Profile","Expansion":"Facility Business License City&State","isSharp":false}],
    ["Facility Business License Expiration Date", {"Source":"Medical Facility Profile","Expansion":"Facility Business License Expiration Date","isSharp":false}],
    ["Facility NPI Number", {"Source":"Medical Facility Profile","Expansion":"Facility NPI #","isSharp":false}],
    ["Facility DEA Number", {"Source":"Medical Facility Profile","Expansion":"Facility DEA #","isSharp":false}],
    ["Fed Tax No", {"Source":"Medical Facility Profile","Expansion":"TIN(EIN) #","isSharp":false}],
    ["Federal Tax ID Number", {"Source":"Medical Facility Profile","Expansion":"TIN(EIN) #","isSharp":false}],
    ["Facility Fax Number", {"Source":"Medical Facility Profile","Expansion":"Facility Fax #","isSharp":false}],
    // ["Hospitalization Dates", {"Source":"Superbill","Expansion":"Hospitalization Dates Related to Current Services","isSharp":true}],
    // ["Outside Lab", {"Source":"Superbill","Expansion":"Outside Lab","isSharp":true}],
    // ["Diagnosis or Nature of Illness or Injury", {"Source":"Superbill","Expansion":"Diagnosis","isSharp":true}],
    // ["Primary Diag Code or Other Diag Code", {"Source":"Superbill","Expansion":"Diagnosis","isSharp":true}],
    // ["Treatment Authorization Codes", {"Source":"Superbill","Expansion":"Prior Authorization Number","isSharp":true}],
    // ["Prior Authorization Number", {"Source":"Superbill","Expansion":"Prior Authorization Number","isSharp":true}],
    // ["Place of Service", {"Source":"Superbill","Expansion":"Place of Service","isSharp":true}],
    // ["Procedures or Services or Supplies", {"Source":"Superbill","Expansion":"Procedure Code, Modifiers","isSharp":true}],
    // ["HCPCS or Rate or HCPCS Code", {"Source":"Superbill","Expansion":"Procedure Code, Modifiers","isSharp":true}],
    // ["Diagnosis Pointers", {"Source":"Superbill","Expansion":"ICD`s","isSharp":true}],
    // ["Charges", {"Source":"Superbill","Expansion":"Procedure Code/Charge","isSharp":true}],
    // ["Days or Unites", {"Source":"Superbill","Expansion":"Quantity","isSharp":true}],
    // ["Srv Units", {"Source":"Superbill","Expansion":"Quantity","isSharp":true}],
    // ["Total Charges", {"Source":"Superbill","Expansion":"Service charge × Quantity = total charge per line","isSharp":true}],
    // ["Service Facility Location information", {"Source":"Superbill","Expansion":"Service Facility Location Information-> Name、address","isSharp":true}],
    // ["Service Facility Location NPI", {"Source":"Superbill","Expansion":"Service Facility Location Information-> NPI","isSharp":true}],
    // ["Service Facility ID", {"Source":"Superbill","Expansion":"Service Facility Location Information-> Tax ID","isSharp":true}],
    // ["Rev Cd", {"Source":"Superbill","Expansion":"Revenue Code","isSharp":true}],
    // ["Description", {"Source":"Superbill","Expansion":"Description","isSharp":true}],
    ["Blood Pressure", {"Source":"Appointment looby>Remote health","Expansion":"Patient Blood Pressure  ","isSharp":false}],
    ["Heart Rate", {"Source":"Appointment looby>Remote health","Expansion":"Patient Heart Rate ","isSharp":false}],
    ["Respiratory Rate", {"Source":"Appointment looby>Remote health","Expansion":"Patient Respiratory Rate","isSharp":false}],
    ["Pulse Oximetry", {"Source":"Appointment looby>Remote health","Expansion":"Patient Pulse Oximetry ","isSharp":false}],
    ["Temperature", {"Source":"Appointment looby>Remote health","Expansion":"Patient Temperature","isSharp":false}],
    ["Blood Glucose levels", {"Source":"Appointment looby>Remote health","Expansion":"Patient Blood Glucose levels  ","isSharp":false}],
    ["Height", {"Source":"Appointment looby>Remote health","Expansion":"Patient Height","isSharp":false}],
    ["Weight", {"Source":"Appointment looby>Remote health","Expansion":"Patient Weight","isSharp":false}],
    ["Body Mass Index(BMI)", {"Source":"Appointment looby>Remote health","Expansion":"Patient Body Mass Index(BMI)","isSharp":false}],
    ["Past Medical History", {"Source":"Appointment looby>Medical History","Expansion":"Past Medical History","isSharp":true}],
    ["Allergies", {"Source":"Appointment looby>Medical History","Expansion":"Allergies","isSharp":true}],
    ["Current Medications", {"Source":"Appointment looby>Medical History","Expansion":"Current Medications","isSharp":true}],
    ["Immunizations", {"Source":"Appointment looby>Medical History","Expansion":"Immunizations","isSharp":true}],
    ["Hospitalizations", {"Source":"Appointment looby>Medical History","Expansion":"Hospitalizations","isSharp":true}],
    ["Surgical History", {"Source":"Appointment looby>Medical History","Expansion":"Surgical History","isSharp":true}],
    ["Family History", {"Source":"Appointment looby>Medical History","Expansion":"Family History","isSharp":true}],
    // ["Obstetrical History", {"Source":"Appointment looby>Medical History","Expansion":"Obstetrical History","isSharp":true}],
    // ["Sexual History", {"Source":"Appointment looby>Medical History","Expansion":"Sexual History","isSharp":true}],
    ["Social History", {"Source":"Appointment looby>Medical History","Expansion":"Social History","isSharp":true}],
    ["Current Time", {"Source":"--","Expansion":"Current Time","isSharp":false}],
    ["Signature", {"Source":"User","Expansion":"User Signature, Signature box","isSharp":true}],
    ["Patients Initials", {"Source": "Signature", "Expansion": "Patients Initials", "isSharp":false}],
    ["Providers Initials", {"Source": "Signature", "Expansion": "Providers Initials", "isSharp":false}],
    ["MAs Initials", {"Source": "Signature", "Expansion": "MAs Initials", "isSharp":false}],
    // ["Vital Sign", {"Source":"Appointment looby>Remote health","Expansion":"Appointment Looby Vital Sign","isSharp":false}],
    ["Patient info", {"Source":"Appointment looby","Expansion":"Patient Name, Date of Birth, Phone #, Email, Patient Address","isSharp":true}],
    ["Provider info", {"Source":"User ","Expansion":"Provider name, Provider title, Provider Specialities, LIC #, NPI #, DEA #\nFacility Email, Fax #, Main #, Address","isSharp":true}],
    ["Facility info", {"Source":"Medical Facility Profile","Expansion":"Medical Facility photo, Name, Address, Email, Website, Main #, Fax #","isSharp":true}],
    ["Diagnosis", {"Source":"--","Expansion":"Diagnosis, Recommend Diagnoses","isSharp":true}],
    // ["Date", {"Source":"undefined","Expansion":"Today Date, Date selection box","isSharp":true}],
    // ["Time", {"Source":"undefined","Expansion":"Time selection box","isSharp":true}],
    ["Input Box(Short)", {"Source": "--", "Expansion": "Input Box(Short)", "isSharp":false}],
    ["Patient Social Security", {"Source": "Appointment lobby ", "Expansion": "Patient Social security #", "isSharp":false}],
    ["Payer Address", {"Source": "Financial Responsibility", "Expansion": "Admin: Primary Insurance Payer Address;  patient/provider: Medical Insurance > Claims address; Workers Comp > Claims address; Personal injury > Attorney address", "isSharp":false}],
    ["Date of Injury", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Date of injury; Personal Injury > Date of injury", isSharp: false}],
    ["Attorney Name", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Attorney name; Personal Injury > Attorney name", isSharp: false}],
    ["Payer Phone Number", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > adjusters phone #; Personal Injury > attorney phone", isSharp: false}],
    ["Payers Fax Number", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > adjusters fax #; Personal Injury > attorney fax #", isSharp: false}],
    ["Adjuster Name", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Claims Adjuster", isSharp: false}],
    ["Adjuster Phone Number", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Adjuster Phone #", isSharp: false}],
    ["Employer Name", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Employer Name", isSharp: false}],
    ["Employers Address", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Employers address", isSharp: false}],
    ["Employers Phone", {"Source": "Financial Responsibility", "Expansion": "Workers Comp > Employers phone #", isSharp: false}],
])

export default DataSource