AiTmedAdmin:
  viewPort: top
  imgDefault: 
    - number: "1"
      path: a_animation1.png
  img1: 
    - number: "1"
      path: a_animation1.png
  img2: 
    - number: "2"
      path: a_animation2.png
  img3: 
    - number: "3"
      path: a_animation3.png
  #laptopOne.png   laptopTwo.png laptop.png
  patientCareList:
    First:
      - img: ellipseBlackBig.png
        width: '20px'
        number: "1"
        top: '0px'
        left: '0px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "2" 
        top: '2px'
        left: '55px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "3"
        top: '2px'
        left: '100px'
    Second:
      - img: ellipseBlackBig.png
        width: '12px'
        number: "1"
        top: '2px'
        left: '5px'
      - img: ellipseBlackBig.png
        width: '20px'
        number: "2"
        top: '0px'
        left: '50px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "3"
        top: '2px'
        left: '105px'
    Third:
      - img: ellipseBlackBig.png
        width: '12px'
        number: "1"
        top: '2px'
        left: '5px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "2"
        top: '2px'
        left: '50px'
      - img: ellipseBlackBig.png
        width: '20px'
        number: "3"
        top: '0px'
        left: '95px'
  formData:
    show:
      - img: ellipseBlackBig.png
        width: '20px'
        number: "1"
        top: '0px'
        left: '0px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "2"
        top: '2px'
        left: '55px'
      - img: ellipseBlackBig.png
        width: '12px'
        number: "3"
        top: '2px'
        left: '100px'
  imgPath: a_animation1.png      
  components:
    - .BaseHeader:
    - type: view
      style: 
        left: "0"
        width: calc(1514.77/1724.81*100vw) 
        margin: auto
        marginTop: calc(102.12/1724.81*100vw) 
      children: 
        - type: view
          viewTag: topView
          style: 
            left: "0"
            height: calc(773/1724.81*100vw) 
            width: calc(1514.77/1724.81*100vw) 
            zIndex: "100"
          children:
            - type: image
              path: adminNew.png
              style: 
                top: "0"
                width: calc(1514.77/1724.81*100vw) 
                left: "0"
            - type: label
              text: "AiTmed Admin"
              style: 
                left: calc(242.365/1724.81*100vw) 
                textShadow: '2px 2px 3px #999999'
                top: calc(222.111/1724.81*100vw) 
                fontSize: calc(38.3/1724.81*100vw) 
                fontWeight: '600'
                color: '0xffffff'
                fontFamily: Arial
            - type: label
              textBoard:
                - text: "Creating the most innovative"
                - br:
                - text: "management system for your practice"
              style: 
                left: calc(242.365/1724.81*100vw) 
                top: calc(300.403/1724.81*100vw) 
                fontSize: calc(25.53/1724.81*100vw) 
                fontFamily: Arial
                color: '0xffffff'
            - type: button
              onClick: 
                - actionType: evalObject
                  object:
                    - goto: https://admin.aitmed.com/
              text: "Get Started - For FREE"
              style:
                fontSize: calc(31/1920*100vw)
                color: '0xffffff'
                fontFamily: 'Arial'
                backgroundColor: "0x30b354" 
                fontWeight: 'Regular'
                borderRadius: calc(4.85/1920*100vw)
                borderWidth: "0"
                boxShadow: 1px 1px 2px 0x000000
                height: calc(65.89/1920*100vw)
                left: calc(14.1vw)
                top: calc(29.25vw)
                padding: "0 20px"
                zIndex: '1000'
                textAlign: 
                  x: center
                  y: center

        - type: view
          style:
            left: "0"
            width: calc(1514.77/1724.81*100vw) 
            height: calc(723.35/1724.81*100vw) 
            background: "linear-gradient(to top ,#054B90, #3890CE)"
            zIndex: "100"
          children:
            - type: label
              text: "AiTmed Admin In Action"
              style: 
                left: calc(378.695/1724.81*100vw) 
                # height: calc(59.57/1724.81*100vw) 
                top: calc(85.1/1724.81*100vw) 
                width: calc(752/1724.81*100vw) 
                fontFamily: "Arial"
                fontWeight: "600"
                fontSize: calc(34.04/1724.81*100vw) 
                color: "#ffffff"
                zIndex: 1000
                textAlign:
                  x: center
            - type: view
              style:
                left: calc(378.695/1724.81*100vw) 
                width: calc(757.39/1724.81*100vw) 
                height: calc(468.05/1724.81*100vw) 
                top: calc(229.77/1724.81*100vw) 
                zIndex: 1000
                textAlign: 
                  x: center
                # backgroundColor: "0xcdcdcd"
              children: 
                - type: list
                  contentType: listObject
                  listObject: ..imgDefault
                  iteratorVar: itemObject
                  viewTag: imgView
                  style:
                    width: calc(757.39/1724.81*100vw) 
                    margin: '0'
                    top: "0"
                    left: "0"
                    height: calc(468.05/1724.81*100vw) 
                  children:
                    - type: listItem
                      itemObject: 
                      onClick: 
                        - emit: 
                            dataKey: 
                              var: itemObject
                            actions: 
                              - if: 
                                - =.builtIn.string.equal: 
                                    dataIn: 
                                      string1: $var.number
                                      string2: "1"
                                - ..imgDefault@: =..img2
                                - continue
                              - if: 
                                - =.builtIn.string.equal: 
                                    dataIn: 
                                      string1: $var.number
                                      string2: "2"
                                - ..imgDefault@: =..img3
                                - continue
                              - if: 
                                - =.builtIn.string.equal: 
                                    dataIn: 
                                      string1: $var.number
                                      string2: "3"
                                - ..imgDefault@: =..img1
                                - continue
                        - actionType: builtIn
                          funcName: redraw
                          viewTag: imgView
                      style:
                        width: calc(757.39/1724.81*100vw) 
                        left: '0'
                      children:
                        - type: image
                          path: 
                            emit:   
                              dataKey: 
                                var: itemObject
                              actions: 
                                - if: 
                                  - true
                                  - $var.path
                                  - $var.path
                          style: 
                            left: calc(151.478/1724.81*100vw) 
                            width: calc(454.434/1724.81*100vw) 
                            top: "0"
                        - type: button
                          text: "Click me!"
                          onClick:
                          style: 
                            top: calc(340.4/1724.81*100vw) 
                            height: calc(68.08/1724.81*100vw) 
                            left: calc(833.129/1724.81*100vw) 
                            width: calc(151.478/1724.81*100vw) 
                            backgroundColor: "#054b90"
                            zIndex: 1000
                            color: "#ffffff"
                            border:
                              style: "5"
                            fontSize: calc(30/1724.81*100vw) 
                            fontWeight: "700"
        - type: view
          style:
            width: calc(1514.77/1724.81*100vw)
            # left: "0"
            display: flex
            justifyContent: center
            alignItems: center
            height: calc(723.35/1724.81*100vw)
            zIndex: "1000"
            backgroundColor: "#ffffff"
          children:
            - type: view
              style:
                width: calc(530.173/1724.81*100vw)
                display: flex
                height: calc(300/1724.81*100vw)
                flexDirection: column
                justifyContent: center
              children:
                - type: image
                  path: lock_bg.png
                  style: 
                    height: calc(256.07/1724.81*100vw)
                    display: flex
            - type: view
              style:
                width: calc(454.434/1724.81*100vw)
                display: flex
                height: calc(550/1724.81*100vw)
                flexDirection: column
                justifyContent: center
              children:        
                - type: label
                  text: 'Blockchain Security & Privacy'
                  style:
                    width: calc(454.434/1724.81*100vw)
                    height: calc(85.1/1724.81*100vw)
                    display: flex
                    fontSize: calc(25.53/1724.81*100vw)
                    fontFamliy: 'Arial'
                    fontWeight: "650"
                    alignItems: center
                - type: label     
                  text: AiTmed Admin is a HIPAA compliant portal full of useful features and benefits with the highest level of security.
                  style: 
                    height: calc(119.14/1724.81*100vw)
                    width: calc(454.434/1724.81*100vw)
                    fontSize: calc(16.17/1724.81*100vw)
                    fontWeight: "450"
                    fontFamliy: 'Arial'
                    # lineHeight: "1.5" 
        - type: view
          style:
            left: "0"
            height: calc(723.35/1724.81*100vw) 
            marginTop: "0"
            width: calc(1514.77/1724.81*100vw) 
            zIndex: "100"
          children: 
            - type: image
              path: adminBottom.png
              style: 
                width: calc(1514.77/1724.81*100vw) 
                top: "0"
                left: "0"
            - type: label
              text: Features
              style: 
                top: calc(119.14/1724.81*100vw) 
                left: calc(681.651/1724.81*100vw) 
                width: calc(151.478/1724.81*100vw) 
                textShadow: ' 1px 1px 2px #999999'
                textAlign:
                  x: center
                color: "#ffffff"
                fontSize: calc(34.04/1724.81*100vw) 
                fontFamily: Arial
                fontWeight: '600'
            - .Box:
              children:
                - type: image
                  path: group1.svg
                  style: 
                    width: calc(60.5912/1724.81*100vw) 
                - .Ltitle:
                - .Lpara:
            - .Box:
              style: 
                left: calc(646.811/1724.81*100vw) 
              children:
                - type: image
                  path: chart.svg
                  style: 
                    width: calc(60.5912/1724.81*100vw) 
                - .Ltitle:
                  text: Modernized EHR and patient management system
                - .Lpara:
                  text: Use our analytics feature to easily see an overview of your facility’s traffic. Update, store, or transfer your patients’ records with one click. A management system can’t get any easier.
            - .Box:
              style:
                left: calc(954.311/1724.81*100vw) 
              children:
                - type: image
                  path: arrow.svg
                  style: 
                    width: calc(60.5912/1724.81*100vw) 
                - .Ltitle:
                  text: Revolutionary one-click e-referral
                - .Lpara:
                  text: AiTmed's premium e-referral network will change the way providers can refer patients to any specialty with ease. Refer patients with any of their medical records, labs, or imaging with speed.
        - type: view
          style:
            marginTop: "0"
            width: calc(1514.77/1724.81*100vw)
            left: "0"
            height: calc(425.5/1724.81*100vw)
            backgroundColor: "transparent"
            zIndex: "1000"
            display: flex
            flexDirection: column
            alignItems: center
            justifyContent: center
          children:
            - type: label
              text: Expand Your Practice Today!
              style:
                height: calc(85.1/1724.81*100vw)
                fontWeight: "600"
                display: flex
                fontSize: calc(42.55/1724.81*100vw)
                #zIndex: "100"
                color: "#000000"
            - type: button
              onClick:
                - goto: https://admin.aitmed.com/
              text: "Sign Up For Free"
              style:
                width: calc(302.956/1724.81*100vw)
                height: calc(42.55/1724.81*100vw)
                fontSize: calc(25.53/1724.81*100vw)
                color: '0xffffff'
                backgroundColor: "0x30b354"
                #zIndex: '100'
                borderRadius: "0.005"
                borderWidth: "0"
                display: flex
                alignItems: center
                justifyContent: center
        - type: view
          style:
            #marginTop: "0" 
            width: calc(1514.77/1724.81*100vw) 
            left: "0" 
            top: calc(2553/1724.81*100vw) 
            height: calc(425.5/1724.81*100vw) 
            #zIndex: "1" 
            #position: "fixed"
            margin: "auto"
          children:
            - type: image
              path: bottomPhoto.png
              style:
                top: "0"
                width: calc(1514.77/1724.81*100vw)
                zIndex: "1"
                position: "fixed"
                opacity: "0.6"
    - .BaseFooter1:





