HaDizziness:
  viewPort: top
  components:
    - .BaseHeader:
    - .HaHeaderViewNew:
      viewTag: topView
      children: 
        - .ImageHa:
        - .HaHeaderBigLabel:
          text: Dizziness
        - .HaHeaderLittleLabel:
          text: Is a common brain dysfunction and one of the most common clinical symptoms.
    - .HaBodyTagView:
      style:
        top: '0.55'
      children:
        - .HaBodyTagButton1:
          text: Dizziness
    - .HaBodyCon:
      style:
        height: '0.65'
        marginTop: '0.23'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Get emergency medical if is accompanied by:"
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              style:
                width: '0.5'
              text: "⦁ Difficulty in breathing"
            - .HaBodyContent:
              style:
                top: '0.05'
              text: "⦁ Chest pain."
            - .HaBodyContent:
              style:
                top: '0.1'
              text: "⦁ Sudden, severe headache."
            - .HaBodyContent:
              style:
                top: '0.15'
                width: '0.5'
              text: "⦁ Numbness or weakness."
            - .HaBodyContent:
              style:
                top: '0.2'
              text: "⦁ Faint."
            - .HaBodyContent:
              style:
                top: '0.25'
              text: "⦁ Blurring or double vision."
            - .HaBodyContent:
              style:
                top: '0.3'
              text: "⦁ Heartbeat is fast or irregular."
            - .HaBodyContent:
              style:
                top: '0.35'
              text: "⦁ Ambiguous or speech difficulties."
            - .HaBodyContent:
              style:
                top: '0.4'
              text: "⦁ Nausea."  
            - .HaBodyContent:
              style:
                top: '0.445'
              text: "⦁ Falling down or walking difficulties."     
            - .HaBodyContent:
              style:
                top: '0.5'
                width: '0.45'
              text: "Dizziness is a term used to describe a range of sensations, such as feeling faint, woozy, weak or unsteady. the common cause of dizziness include"
                             
        - .HaBodyImg:
          style:  
            top: '0.115'
            left: '0.69'
            width: '0.16'
          path: healthAZ/dizziness.png
    - .HaBodyCon:
      style:
        height: '0.58'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Inner ear problems that cause dizziness"
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              text: "⦁ Benign paroxysmal positional vertigo (BPPV). Commonly known as 'tolith', the prevalence rate is about 2.4%, and the incidence increases gradually with age. The exact pathogenesis is still unclear. This condition causes an intense and brief but false sense that you're spinning or moving. These episodes are triggered by a rapid change in head movement, such as when you turn over in bed, sit up or experience a blow to the head. BPPV is the most common cause of vertigo."
            - .HaBodyContent:
              style:
                top: '0.12'
              text: "⦁ Meniere's disease (Ménière's syndrome). Also known as membrane lost water, is an unexplained inner ear disease with idiopathic endolymphatic hydrops as the main pathological feature. It's characterized by sudden episodes of vertigo lasting as long as several hours. You may also experience fluctuating hearing loss, ringing in the ear and the feeling of a plugged ear."
            - .HaBodyContent:
              style:
                top: '0.24'
              text: "⦁ lost to the road. Labyrinthitis, also known as otitis media, is a common complication of suppurative otitis media. According to the extent of lesions and changes in disease course, it can be divided into three types: localized labyrinthitis, serous labyrinthitis and suppurative labyrinthitis. The degree of dizziness is gradually aggravated, and both are accompanied by hearing loss."
            - .HaBodyContent:
              style:
                top: '0.36'
                # width: '0.5'
              text: "⦁ Migraine vertigo (vestibular migraine) Migraine vertigo is the most common central vestibular dysfunction. People who experience migraines may have episodes of vertigo or other types of dizziness even when they're not having a severe headache. Such vertigo episodes can last minutes to hours and may be associated with headache as well as light and noise sensitivity."

    - .HaBodyCon:
      style:
        height: '0.3'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Dizziness caused by Circulation problems"
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              text: "⦁ low blood pressure. The characteristics are: dizziness or syncope when standing for too long, fatigue, hunger or sudden standing. It can be relieved after a short rest in the supine, often accompanied by tinnitus, but no hearing loss; and lack of inner ear and brain Blood-related, mild hypotension causes dizziness due to mild cerebral ischemia and hypoxia;"
            - .HaBodyContent:
              style:
                top: '0.12'
              text: "⦁ Poor blood circulation. Conditions such as cardiomyopathy, heart attack, heart arrhythmia and transient ischemic attack could cause dizziness. And a decrease in blood volume may cause inadequate blood flow to your brain or inner ear thus causes the symptom."
            
    - .HaBodyCon:
      style:
        height: '0.43'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Other causes of dizziness"
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              text: "⦁ Extraocular muscle paralysis. Congenital dysplasia or acquired traumatic eye disease caused by extraocular muscle paralysis, leading to visual afferent defects, the actual visual afferent information and the expected incoming information have a contradiction, resulting in pathological visual vertigo."
            - .HaBodyContent:
              style:
                top: '0.09'
              text: "⦁ Mental dizziness. refers to vertigo caused by anxiety and other mental disorders. Its clinical features are: dizziness exists almost every day, is persistent, can be accompanied by panic attacks and other mental appearance."
            - .HaBodyContent:
              style:
                top: '0.15'
              text: "⦁ Medications. Dizziness can be a side effect of certain medications — such as anti-seizure drugs, antidepressants, sedatives and tranquilizers. In particular, blood pressure lowering medications may cause faintness if they lower your blood pressure too much"
            - .HaBodyContent:
              style:
                top: '0.24'
                width: '0.5'
              text: "⦁ Low blood sugar (hypoglycemia). This condition generally occurs in people with diabetes who use insulin. Dizziness (lightheadedness) may be accompanied by sweating and anxiety."        


    - .HaBodyCon:
      style:
        height: '0.25'
      children:
        - .HaHeaderView:
          style: 
            width: '0.68'
            height: '0.25'
          children:
            - .HaHeaderBigLabel1:
              style: 
                top: '0.0125'
                left: '0.05'
                height: '0.125'
                textAlign: 
                  y: center
                fontFamily: "Arial"
                fontStyle: "bold"
                fontSize: .Sfont.h4
              text: SPEAK WITH A DOCTOR
            - .HaHeaderLittleLabel1:
              style: 
                top: '0.1'
                width: '0.58'
                fontFamily: "Arial"
                height: '0.125'
                textAlign: 
                  y: center
                fontStyle: "bold"
                fontSize: .Sfont.h3
                left: '0.05'
              text: If Dizziness is interfering with your daily life, log on AITMED and talk to a doctor to receive a treatment plan customized for you.

    - type: view
      style:
        height: '0.25'
        left: '0'
        marginTop: '0.05'
        width: '1'
      children:
        - .HaBottomTag: 
          # style:
          #   left: '0.34'
        - .HaBottomTagname: 
          style: 
            # width: '0.15'
            # left: '0.5'
          # text: "Dizziness"
    - .BaseFooter1:







