HaNumbnessOrTinglingInHands:
  viewPort: top
  components:
    - .BaseHeader:
    - .HaHeaderViewNew:
      viewTag: topView
      children: 
        - .ImageHa:
        - .HaHeaderBigLabel:
          text: Numbness or tingling in hands
        - .HaHeaderLittleLabel:
          text: These symptoms are referred to as paresthesia of the fingers.
    - .HaBodyTagView:
      style: 
        marginTop: '0.09'
      children:
        - .HaBodyTagButton1:
          text: pelvic
    - .HaBodyCon:
      style:
        height: '0.3'
        marginTop: '0.23'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Get emergency care if your child:"
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              style:
                width: '0.5'
              text: "⦁ Began suddenly"
            - .HaBodyContent:
              style:
                top: '0.05'
              text: "⦁ Follows an injury or accident"
            - .HaBodyContent:
              style:
                top: '0.1'
              text: "⦁ Is accompanied by weakness or paralysis"
            - .HaBodyContent:
              style:
                top: '0.15'
                width: '0.5'
              text: "⦁ Is accompanied by confusion or difficulty speaking"
            - .HaBodyContent:
              style:
                top: '0.2'
              text: "⦁ Is accompanied by dizziness or lightheadedness"
           

        - .HaBodyImg:
          style:  
            top: '0.11'
            left: '0.68'
            width: '0.16'
          path: healthAZ/numbness-or-tingling-in-hands.png
    - .HaBodyCon:
      style:
        height: '0.63'
      children:
        - .HaBodyTitle:
          style:
            width: '0.68'
          text: "Find possible causes of numbness or tingling in hands based on specific factors. Use our patient Questionnaire."
        - type: view
          style:
            marginTop: '0.05'
          children:
            - .HaBodyContent:
              text: "Numbness in one or both hands describes a loss of sensation or feeling in your hand or fingers. Often, hand numbness may be accompanied by other changes, such as a pins-and-needles sensation, burning or tingling. Your arm, hand or fingers may feel clumsy or weak."
            - .HaBodyContent:
              style:
                top: '0.1'
              text: "Pinched nerve is a common cause of Numbness or tingling in hands .A pinched nerve occurs when too much pressure is applied to a nerve by surrounding tissues, such as bones, cartilage, muscles or tendons. This pressure disrupts the nerve's function, causing pain, tingling, numbness or weakness. A pinched nerve can occur at a number of sites in your body. A herniated disk in your lower spine, for example, may put pressure on a nerve root, causing pain that radiates down the back of your leg. Likewise, a pinched nerve in your wrist can lead to pain and numbness in your hand and fingers (carpal tunnel syndrome). With rest and other conservative treatments, most people recover from a pinched nerve within a few days or weeks. Sometimes, surgery is needed to relieve pain from a pinched nerve."
            - .HaBodyContent:
              style:
                top: '0.31'
              text: "Diseases affecting the peripheral nerves, such as diabetes, also can cause numbness, although with diabetes similar symptoms usually occur first in your feet."
            - .HaBodyContent:
              style:
                top: '0.38'
                
              text: "In very uncommon instances, numbness can be caused by problems in your brain or spinal cord, although in such cases arm or hand weakness or loss of function also occurs. Numbness alone is only rarely associated with potentially life-threatening disorders, such as strokes or tumors."
            

   
    
    - .HaBodyCon:
      style:
        height: '0.25'
      children:
        - .HaHeaderView:
          style: 
            width: '0.68'
            height: '0.25'
          children:
            - .HaHeaderBigLabel1:
              style: 
                top: '0.0125'
                left: '0.05'
                height: '0.125'
                textAlign: 
                  y: center
                fontFamily: "Arial"
                fontStyle: "bold"
                fontSize: .Sfont.h4
              text: SPEAK WITH A DOCTOR
            - .HaHeaderLittleLabel1:
              style: 
                top: '0.1'
                width: '0.58'
                fontFamily: "Arial"
                height: '0.125'
                textAlign: 
                  y: center
                fontStyle: "bold"
                fontSize: .Sfont.h3
                left: '0.05'
              text: If Numbness or tingling in hands is interfering with your daily life, log on AITMED and talk to a doctor to receive a treatment plan customized for you.

    - type: view
      style:
        height: '0.25'
        left: '0'
        marginTop: '0.05'
        width: '1'
      children:
        - .HaBottomTag: 
        - .HaBottomTagname: 
          # text: "pelvic" 
    - .BaseFooter1:












