export const textSharpSplitChar = `|-|`
export const textSharpRegStr = `#[\\w*]+\\|\\-\\|((?!\\|\\-\\|).)+\\|\\-\\|((?!\\|\\-\\|).)+\\|\\-\\|`
export const textSharpGetReg = />#[\w*]+\|-\|((?!\|-\|).)+\|-\|((?!\|-\|).)+\|-\|</g
export const textSharpSplitRegG = /\|-\|/g
export const textSharpSplitReg = /\|-\|/
export const textSharpReg = /#[\w*]+\|-\|((?!\|-\|).)+\|-\|((?!\|-\|).)+\|-\|/
export const choiceSharpReg = /#[\w *\$\&]+\|-\|((?!\|-\|).)+\|-\|/
export const choiceSharpRegStr = `#[\\w *\\$\\&]+\\|\\-\\|((?!\\|\\-\\|).)+\\|\\-\\|`
export const choiceSharpGetReg = />#[\w *\$\&]+\|-\|((?!\|-\|).)+\|-\|</g
export const choiceArrayStr = `\\|\\-\\|(((?!\\|\\-\\|).)*\\|\\-\\|[a-z]*\\|\\-\\|)+`