Products:
  title: "Products"
  
  pageNumber: 
  
  init: 

  formData: 
  
  formDataTemp: 

  apiRequest: 

  style:
    productTypeView:  #  包裹AiTMedicine和AiTOffice的上下两个view
      type: view
      style: 
        width: "0.7"
        height: "0.38"
        # backgroundColor: "0xcdcdcd"

    productTypeLabel:  # 文本：AiTMedicine和AiTOffice的样式
      type: label
      style: 
        left: "0"
        top: "0.02"
        width: "10vw"
        height: "0.03"
        fontSize: "0.9vw"
        fontFamily: Poppins
        textAlign: 
          x: left

    productTypeOuterView:  #  包裹AiTMedicine和AiTOffice的里面具体的三个块的view
      type: view
      style: 
        top: "0.06"
        left: "0"
        width: "0.7"
        height: "0.32"
        display: flex
        flexWrap: wrap
        justifyContent: space-between
        # backgroundColor: "0xff0000"

    productTypeInnerView:  #  三个块view的具体
      type: view
      style: 
        width: "0.2"
        height: "0.32"
        borderRadius: "5"
        backgroundColor: "0xf6fafe"
        display: flex
        flexWrap: wrap
        justifyContent: center
        boxShadow: "0px 3px 2px 2px #f1f1f1"

    productTypeInnerImg: 
      type: image
      path: aitmedLogoWhite.svg
      style: 
        marginTop: "0.015"
        width: "0.055"

    productTypeInnerTitle: 
      type: label
      text: AiTmed Patient
      style: 
        width: "0.2"
        height: "0.03"
        fontSize: "0.8vw"
        # flexGrow: "2"
        fontFamily: Poppins
        textAlign: 
          x: center
          y: center

    productTypeInnerLabel: 
      type: label
      text: Description goes there,you have description up to three lines if needed
      style: 
        width: "0.14"
        height: "0.045"
        fontSize: "0.65vw"
        fontFamily: sans-serif
        textAlign: 
          x: center

    productTypeInnerButtonView:  # 两个按钮的view
      type: view
      style: 
        width: "0.15"
        height: "0.04"
        borderRadius: "5"
        # backgroundColor: "0xff0000"
        display: flex
        flexWrap: wrap
        justifyContent: space-between
    
    productTypeInnerButton:  # show plan 和 edit product两个按钮
      type: button
      text: Show Plan
      style: 
        width: "0.07"
        height: "0.035"
        fontSize: "0.6vw"
        color: "0x707070"
        fontFamily: Poppins
        backgroundColor: "0xefefef"
        border: 
          style: "5"
        borderRadius: "4"
        textAlign: 
          x: center

  components:
    - .TotalView: 
      children: 
        - .SideMenuBar: 
        - .BodyView: 
          children:
            - .TopBar: 
            - .InnerBodyView:
              children:
                - .PageTitle:
                - .ContentView:
                  style: 
                    display: flex
                    flexWrap: wrap
                    justifyContent: space-around
                    alignContent: flex-start
                  children:
                    - ..style.productTypeView: 
                      children: 
                        - ..style.productTypeLabel: 
                          text: AiTMedicine
                        - ..style.productTypeOuterView:
                          children: 
                            - ..style.productTypeInnerView:
                              children: 
                                - ..style.productTypeInnerImg: 
                                - ..style.productTypeInnerTitle: 
                                - ..style.productTypeInnerLabel: 
                                - ..style.productTypeInnerButtonView: 
                                  children: 
                                    - ..style.productTypeInnerButton: 
                                    - ..style.productTypeInnerButton:
                                      text: Edit Product 
                                      onClick: 
                                        - actionType: popUp
                                          popUpView: editProductView
                                      style: 
                                        backgroundColor: "0x005795"
                                        color: "0xffffff"
                            - ..style.productTypeInnerView:
                              children: 
                                - ..style.productTypeInnerImg: 
                                - ..style.productTypeInnerTitle: 
                                  text: AiTmed Provider
                                - ..style.productTypeInnerLabel: 
                                - ..style.productTypeInnerButtonView: 
                                  children: 
                                    - ..style.productTypeInnerButton: 
                                    - ..style.productTypeInnerButton:
                                      text: Edit Product 
                                      style: 
                                        backgroundColor: "0x005795"
                                        color: "0xffffff"                            
                            - ..style.productTypeInnerView:
                              children: 
                                - ..style.productTypeInnerImg: 
                                - ..style.productTypeInnerTitle: 
                                  text: AiTmed Admin
                                - ..style.productTypeInnerLabel: 
                                - ..style.productTypeInnerButtonView: 
                                  children: 
                                    - ..style.productTypeInnerButton: 
                                    - ..style.productTypeInnerButton:
                                      text: Edit Product 
                                      style: 
                                        backgroundColor: "0x005795"
                                        color: "0xffffff"                            
                    - ..style.productTypeView: 
                      children: 
                        - ..style.productTypeLabel: 
                          text: AiTOffice
                        - ..style.productTypeOuterView:
                          style: 
                            width: "0.45"
                          children: 
                            - ..style.productTypeInnerView:
                              children: 
                                - ..style.productTypeInnerImg: 
                                  path: aitMeet.svg
                                - ..style.productTypeInnerTitle: 
                                  text: AiTmeet
                                - ..style.productTypeInnerLabel: 
                                - ..style.productTypeInnerButtonView: 
                                  children: 
                                    - ..style.productTypeInnerButton: 
                                    - ..style.productTypeInnerButton:
                                      text: Edit Product 
                                      style: 
                                        backgroundColor: "0x005795"
                                        color: "0xffffff"                            
                            - ..style.productTypeInnerView:
                              children: 
                                - ..style.productTypeInnerImg: 
                                  path: prnote.svg
                                - ..style.productTypeInnerTitle: 
                                  text: Prynote
                                - ..style.productTypeInnerLabel: 
                                - ..style.productTypeInnerButtonView: 
                                  children: 
                                    - ..style.productTypeInnerButton: 
                                    - ..style.productTypeInnerButton:
                                      text: Edit Product 
                                      style: 
                                        backgroundColor: "0x005795"
                                        color: "0xffffff"                            
        - .BaseDetailPop: 
          viewTag: editProductView
          children: 
            - .BaseDetailPopView: 
              children: 
                - .BaseDetailPopImg: 
                - .BaseDetailPopLabel: 
                  text: Change Product Information
                - .BaseDetailPopInnerView:
                  style: 
                    display: flex
                    width: "0.28"
                    left: "0.05"
                    justifyContent: center
                    flexWrap: wrap
                    alignContent: 
                  children: 
                    - type: image
                      path: camera.svg
                      style: 
                        width: "0.06"
                        height: "0.13"
                    - type: view
                      style: 
                        width: "0.28"
                        height: "0.2"
                        display: flex
                        flexWrap: wrap
                        justifyContent: center
                      children: 
                        - type: label
                          text: Product Name
                          style: 
                            width: "0.28"
                            fontSize: "0.8vw"
                        - type: textField
                          style: 
                            width: "0.28"
                            height: "0.04"
                            border: 
                              style: "3"
                            borderWidth: "1"
                            borderColor: "0xebebeb"
                            borderRadius: "4"
                            boxSizing: border-box
                        - type: label
                          text: Description
                          style: 
                            width: "0.28"
                            fontSize: "0.8vw"
                        - type: textView
                          style: 
                            width: "0.28"
                            height: "0.08"
                            border: 
                              style: "3"
                            borderWidth: "1"
                            borderColor: "0xebebeb"
                            borderRadius: "4"
                            boxSizing: border-box
                    - type: view
                      style: 
                        width: "0.28"
                        height: "0.06"
                        display: flex
                        flexWrap: nowrap
                        justifyContent: space-between
                      children:         
                        - type: button
                          text: Cancel
                          onClick: 
                            - actionType: popUpDismiss
                              popUpView: editProductView
                          style: 
                            width: "0.1"
                            height: "0.04"
                            fontSize: "0.9vw"
                            color: "0xffffff"
                            fontFamily: Poppins
                            backgroundColor: "0xc1c1c1"
                            border: 
                              style: "5"
                            borderRadius: "4"
                            textAlign: 
                              x: center 
                        - type: button
                          text: Save
                          style: 
                            width: "0.1"
                            height: "0.04"
                            fontSize: "0.9vw"
                            color: "0xffffff"
                            fontFamily: Poppins
                            backgroundColor: "0x005795"
                            border: 
                              style: "5"
                            borderRadius: "4"
                            textAlign: 
                              x: center                               