export declare const lf: LocalForage;
export declare function clear(): Promise<void>;
export declare function each(cb: (key: string, value: unknown, index: number) => Promise<any>): Promise<void>;
export declare function getKeys(): Promise<string[]>;
export declare function getKeyCount(): Promise<number>;
export declare function getItem(key?: string): Promise<unknown>;
export declare function setItem(key: string, value: any): Promise<void>;
export declare function supportsIndexedDB(): boolean;
export declare function supportsWebSQL(): boolean;
export default lf;
