ProductDetails:
  title: Product Details
  init:
    - actionType: evalObject
      object:
        - actionType: evalObject
          async: true
          object:
            - =..apiRequest.assetsAboutProduction.docAPI.get: ""
            - =..apiRequest.productVideoImage.docAPI.get: ""
            - =..apiRequest.productVideo.docAPI.get: ""
            - =..apiRequest.productCoverImage.docAPI.get: ""
    - if:
        - =.builtIn.array.judgeListLength:
            dataIn:
              array: =..apiRequest.productVideoImage.docQueryResp.doc
              len: 0
        - continue
        - actionType: evalObject
          object:
            - =.builtIn.utils.getImgByDocIds:
                dataIn:
                  ids:
                    - =..apiRequest.productVideoImage.docQueryResp.doc.0.id
                dataOut: ProductDetails.formData.productCoverImageUrlList
            - ..formData.productCoverImageUrl@: =..formData.productCoverImageUrlList.0.path
    - =.builtIn.array.SortBy:
        dataIn:
          object: =..apiRequest.assetsAboutProduction.docQueryResp.doc
          iterate: ["name.title"]
          orders: ["asc"]
        dataOut: ProductDetails.apiRequest.assetsAboutProduction.docQueryResp.doc
    - if:
        - =.builtIn.array.judgeListLength:
            dataIn:
              array: =..apiRequest.productCoverImage.docQueryResp.doc
              len: 0
        - continue
        - =.builtIn.array.push:
            dataIn:
              newMessage: =..apiRequest.productCoverImage.docQueryResp.doc.0
              messages: =..apiRequest.assetsAboutProduction.docQueryResp.doc
    - if:
        - =.builtIn.array.judgeListLength:
            dataIn:
              array: =..apiRequest.productVideo.docQueryResp.doc
              len: 0
        - continue
        - =.builtIn.array.push:
            dataIn:
              newMessage: =..apiRequest.productVideo.docQueryResp.doc.0
              messages: =..apiRequest.assetsAboutProduction.docQueryResp.doc
    - =.builtIn.object.extract:
        dataIn:
          array: =..apiRequest.assetsAboutProduction.docQueryResp.doc
          field: id
        dataOut: ProductDetails.formData.assetIdsAboutProduction
    - =.builtIn.utils.getImgByDocIds:
        dataIn:
          ids: =..formData.assetIdsAboutProduction
        dataOut: ProductDetails.formData.assetIdsAboutProduction1
  formData:
    # 商品视频首页图片数组
    productCoverImageUrlList: []
    # 商品视频首页图片
    productCoverImageUrl: ""
    assetIdsAboutProduction: []
    assetIdsAboutProduction1: []
  apiRequest:
    shopCartUnderCurrentAppointment:
      docQueryResp:
        doc: []
      docQueryReq:
        id: .Global.currentRoomInfo.edge.id
        xfname: eid
        type: .DocType.Order
        sCondition: tage = 0
        obfname: ctime
        _nonce: =.Global._nonce
      docAPI:
        get:
          api: rd
          dataIn: ProductDetails.apiRequest.shopCartUnderCurrentAppointment.docQueryReq
          dataOut: ProductDetails.apiRequest.shopCartUnderCurrentAppointment.docQueryResp
    productVideoImage:
      docQueryResp:
      docQueryReq:
        id: .Global.formData.production.id
        xfname: reid
        type: .DocType.ProductVideoImage
        obfname: ctime
        maxcount: 1
        _nonce: .Global._nonce
      docAPI:
        get:
          api: rd
          dataIn: ProductDetails.apiRequest.productVideoImage.docQueryReq
          dataOut: ProductDetails.apiRequest.productVideoImage.docQueryResp
    productVideo:
      docQueryResp:
      docQueryReq:
        id: .Global.formData.production.id
        xfname: reid
        type: .DocType.ProductVideo
        obfname: ctime
        maxcount: 1
        _nonce: .Global._nonce
      docAPI:
        get:
          api: rd
          dataIn: ProductDetails.apiRequest.productVideo.docQueryReq
          dataOut: ProductDetails.apiRequest.productVideo.docQueryResp
    productCoverImage:
      docQueryResp:
      docQueryReq:
        id: .Global.formData.production.id
        xfname: reid
        obfname: ctime
        maxcount: 1
        type: .DocType.ProductCoverImage
        _nonce: .Global._nonce
      docAPI:
        get:
          api: rd
          dataIn: ProductDetails.apiRequest.productCoverImage.docQueryReq
          dataOut: ProductDetails.apiRequest.productCoverImage.docQueryResp
    assetsAboutProduction:
      docQueryResp:
      docQueryReq:
        id: .Global.formData.production.id
        xfname: reid
        type: .DocType.ProductDetailImage
        _nonce: .Global._nonce
      docAPI:
        get:
          api: rd
          dataIn: ProductDetails.apiRequest.assetsAboutProduction.docQueryReq
          dataOut: ProductDetails.apiRequest.assetsAboutProduction.docQueryResp
  formDataTemp:
    data:
      option: {
          borderRadius: 10,
          spaceBetween: 0,
          direction: "vertical",
          loop: true,
          autoplay: { delay: 2000 },
          effect: "slide",
          # pagination: true,
          pagination: { type: "bullets" },
          # type: "bullets",
          # clickable: true
          navigation: false,
          slidesPerView: 1,
          childStyle: { width: "31.64vh" },
        }
  components:
    - .BasePublicHeader:
        children:
          - .BasePublicHeaderLeft:
          - .BasePublicHeaderTitle:
    - type: scrollView
      style:
        ..style.scrollBox:
      children:
        - type: view
          style:
            ..style.rotationBox:
          children:
            - type: rotation
              dataKey: formData.assetIdsAboutProduction1
              dataOption: formDataTemp.data.option
              style:
                ..style.rotation:
        - type: view
          style:
            ..style.goodsBox:
          children:
            - type: label
              dataKey: Global.formData.production.name.data.priceRange
              style:
                ..style.price:
            - type: label
              dataKey: Global.formData.production.name.data.basicInfo.type
              style:
                ..style.value:
                color: .Global.formData.production.name.data.basicInfo.typeColor
        - type: label
          dataKey: Global.formData.production.name.data.basicInfo.title
          style:
            ..style.title:
        - type: label
          textBoard:
            - text: "Vendor:"
            - text: "&nbsp;"
            - text: ""
              dataKey: Global.formData.production.name.data.basicInfo.vendor
          dataKey:
          style:
            ..style.vendor:
        - type: label
          dataKey: Global.formData.production.name.data.basicInfo.introduction
          style:
            ..style.describe:
        - type: list
          viewTag: dataListTag
          contentType: listObject
          listObject: .Global.formData.production.name.data.options.optionsValue
          iteratorVar: itemObject
          style:
            ..style.list:
          children:
            - type: listItem
              itemObject:
              style:
                ..style.listItem:
              children:
                - type: view
                  style:
                    ..style.selectBox:
                  children:
                    - type: label
                      dataKey: itemObject.styleName
                      style:
                        ..style.optionTitle:
                    - type: view
                      style:
                        ..style.optionBox:
                      children:
                        - type: list
                          androidFlex: true
                          contentType: listObject
                          listObject: itemObject.styleValue
                          iteratorVar: itemObject
                          style:
                            ..style.optionList:
                          children:
                            - type: listItem
                              itemObject:
                              style:
                                ..style.optionListItem:
                              children:
                                - type: label
                                  dataKey: itemObject.value
                                  style:
                                    ..style.optionBtn:

        - type: view
          style:
            marginTop: "0.03"
    - type: view
      style:
        ..style.btnBox:
      children:
        - type: button
          text: Add Medical Product
          dataKey:
          style:
            ..style.btn:
          onClick:
            - ..event.selectClick
  event:
    selectClick:
      - actionType: evalObject
        object:
          # 将production的id存入推荐文档中
          - =.builtIn.array.pushAny:
              dataIn:
                newMessage: =.Global.formData.production.id
                messages: =.Global.formData.productionSelectionList
              dataOut: Global.formData.productionSelectionList
          # 放入当前商品名
          - =.builtIn.array.pushAny:
              dataIn:
                newMessage: =.Global.formData.production.name.data.basicInfo.title
                messages: =.Global.formData.goodNameList
              dataOut: Global.formData.goodNameList
      - actionType: builtIn
        funcName: goBack
        reload: true
  style:
    scrollBox:
      width: "1"
      height: "0.84729"
      boxSizing: "border-box"
      overflow: "scroll"
      paddingBottom: "0.03"
    btnBox:
      width: "1"
      height: "0.0972"
      boxSizing: "border-box"
      overflow: "scroll"
      backgroundColor: "#ffffff"
      boxShadow: "1px 1px 4px 1px #dededf"
    list:
      width: "0.92"
      margin: "0"
      marginLeft: "0.04"
      height: "auto"
      boxSizing: "border-box"
    listItem:
      width: "0.92"
      height: "auto"
      boxSizing: "border-box"
      overflow: hidden
    selectBox:
      ..style.publickBox:
      marginTop: "0.022167"
    optionTitle:
      marginTop: "0.014778"
      fontSize: .Nfont.h14
      color: "#333333"
      display: "inline-block"
      width: "0.1533333"
    optionBox:
      display: "inline-block"
    optionList:
      margin: "0"
      height: auto
      width: "0.7653327"
    optionListItem:
      display: "inline-block"
      marginLeft: "0.0373333"
      marginTop: "0.014778"
      height: "auto"
      width: "auto"
      boxSizing: "border-box"
      backgroundColor: "#f5f5f5"
      borderRadius: "4"
    optionBtn:
      fontSize: .Nfont.h12
      height: "auto"
      paddingLeft: "0.026"
      paddingRight: "0.026"
      paddingTop: "0.007"
      paddingBottom: "0.007"
      width: "auto"
      boxSizing: "border-box"
      textAlign:
        x: center
        y: center
    btn:
      marginTop: "0.0123"
      marginLeft: "0.08"
      height: "0.0443"
      width: "0.84"
      border:
        style: 1
      borderRadius: "5"
      backgroundColor: "#2988e6"
      color: "#ffffff"
      fontSize: .Nfont.h14
      boxSizing: border-box
      fontWeight: "600"
      textAlign:
        x: center
    rotationBox:
      width: "1"
      height: "0.315270"
      backgroundColor: "#ffffff"
    rotation:
      width: "1"
      height: "0.315270"
      margin: 0
      padding: 0
    img:
      width: "1"
      height: "0.315270"
    goodsBox:
      marginLeft: "0.04"
      marginTop: "0.0270935"
      width: "0.92"
      height: "auto"
    price:
      display: "inline-block"
      fontWeight: "700"
      fontSize: .Nfont.h16
      color: "#fb5051"
      width: "0.7"
      verticalAlign: middle
      boxSizing: border-box
    value:
      marginLeft: "0.02"
      display: "inline-block"
      width: "0.2"
      color: =..formData.type.color
      fontSize: .Nfont.h12
      fontWeight: "700"
      verticalAlign: middle
      boxSizing: border-box
      textAlign:
        x: right
    title:
      marginLeft: "0.04"
      marginTop: "0.014778"
      width: "0.92"
      height: "auto"
      wordWrap: break-word
      fontSize: .Nfont.h14
      fontWeight: "600"
      color: "#333333"
    vendor:
      marginTop: "0.01"
      marginLeft: "0.04"
      width: "0.92"
      height: "auto"
      fontSize: .Nfont.h12
      fontWeight: "600"
      color: "#666666"
    describe:
      marginTop: "0.0270935"
      marginLeft: "0.04"
      width: "0.92"
      height: "auto"
      wordWrap: break-word
      color: "#333333"
      fontSize: .Nfont.h14
      lineHeight: "2.58vh"
