ScheduleSettings: # xd page number64
  pageNumber: "370"
  init:
    - .SignInCheck
    - actionType: evalObject
      object:
        .Global._nonce@:
          =.builtIn.math.random: ""
    - ..providerList.docAPI.get
  viewPort: top
  title: "ScheduleSettings"
  providerList:
    list: ""
    docAPI:
      get: 
        api: rd
        dataKey: providerList.list
        ObjType: 12
        type: .DocType.DoctorProfile
        id: .Global.currentFacility.id
        xfname: E.bvid|E.evid
        sCondition: E.type=10002 AND E.tage=1
        maxcount: "10000"
        _nonce: =.Global._nonce
  components:
    - .SideMenuBar:
      children:
        - .aitLogo:
        - .MenuBar:
    - .TopBar:
    - .BodyView:
      children:
        - type: view
          style:  
            left: "0.03"
            top: "0.01"
            width: "0.2"
            height: "0.06"
          children: 
            - .ProviderButton: 
              text: Facility Info
              style:
                fontSize: "15"                           
              onClick: 
                - goto: FacilityInfo1
            - .ProviderButton: 
              text: ScheduleSettings
              onClick: 
                - goto: ScheduleSettings
              style:
                left: "0.1"
                backgroundColor: "#003D68"
                color: "0xffffff"
                textDecoration: underline
                fontSize: "15"
    - .ContentView:
      style: 
        height: "0.82"
        left: "0.19"
        top: "0.145"
      children:
        - type: label
          text: "Providers Availability"
          style:
            fontSize: "16"
            left: "0.02"
            top: "0.04"
        - type: label
          text: "Select a provider to edit or update their schedule availability settings."
          style:
            fontSize: "13"
            left: "0.02"
            top: "0.08"
            color: "#757575"                                         
        - type: scrollView
          scrollBar: "false"
          style:
            height: "0.7"
            width: '0.78'
            top: "0.12"
            overflowY: scroll
          children:
            - type: list
              contentType: listObject
              listObject: ..providerList.list.doc
              iteratorVar: itemObject
              style:
                width: '0.78'
                height: '0.7'
                float: left
              children:
                - type: listItem
                  onClick:
                    - emit:
                        dataKey:
                          var: itemObject
                        actions:
                          - .Global.acceptInfo@: ""
                          - .Global.acceptInfo@: $var
                    # - actionType: evalObject
                    #   dataObject: .Global.acceptInfo
                    #   dataKey:  itemObject
                    - goto: ProfileAvailability
                  itemObject: 
                  style:
                    display: inline-block
                    width: '0.19'
                    height: '0.35'
                    left: '0'
                  children:
                    - .Scview:
                      children:
                        - type: image
                          # path=func: .builtIn.utils.prepareDocToPath
                          path: ava.png
                        # - type: ecosDoc
                        #   ecosObj: itemObject.name.inviteeAvatar
                          style:
                            width: "0.06"
                            left: "0.06"
                            top: "0.06"
                          dataKey: itemObject.name.inviteeAvatar

                        # - .Sclabel:
                        - .ScLabel:
                          dataKey: itemObject.name.data.fullName
                        - .ScLabel0:
                          text: Provider
                          # text: "Eiliyah Golden,MD"                       
            