function getTagName(type: string) {
  return {
    span: 'span',
    br: 'br',
    button: 'button',
    canvas: 'canvas',
    chart: 'div',
    date: 'input',
    dateSelect: 'input',
    divider: 'hr',
    ecosDoc: 'div',
    footer: 'div',
    header: 'div',
    searchBar: 'input',
    textField: 'input',
    image: 'img',
    label: 'div',
    list: 'ul',
    listItem: 'li',
    map: 'div',
    page: 'iframe',
    popUp: 'div',
    plugin: 'div',
    pluginHead: 'script',
    pluginBodyTail: 'script',
    register: 'div',
    scrollView: 'div',
    select: 'select',
    textView: 'textarea',
    video: 'video',
    view: 'div',
    table: "table",
    tr: "tr",
    td: "td",
    th: "th",
  }[type]
}

export default getTagName
